name: ntds_2017
channels:
- conda-forge
- defaults
dependencies:
- git
- python
- numpy
- scipy
- pandas
- matplotlib
- seaborn
- scikit-learn
- networkx=1.11
- tweepy=3.5.0
- requests
- tqdm
- statsmodels
- librosa=0.5.1
- ffmpeg
- ipython
- jupyter
- jupyterlab_launcher=0.5.0
- pygsp==0.5.1
